name: Test Secret
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Check SECRET_KEY
        run: echo "SECRET_KEY is ${{ secrets.SECRET_KEY }}"
