name: test_Django
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
 # activates the workflow when there is a push or pull request in the repo
env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
jobs:
  test_project:
    runs-on: ubuntu-latest # operating system your code will run on
    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt # install all our dependencies for the project       
      - name: Lint with ruff
        run: |
          pip install ruff
          ruff format
          ruff check --output-format=github .
        continue-on-error: true
      - name: run tests  
        run: |
          cd todo_app_api
          python manage.py makemigrations
          python manage.py migrate
          python manage.py test
      
      

