name: Test Secret
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - name: Set env as secret
       env:
        MY_VAL: ${{ secrets.DJANGO_SECRET }}
       run: |
        import os
        data = open("file", "w")
        for q in (os.getenv("MY_VAL")):
          print(q)
          data.write(q)
       shell: python
