name: test_Django
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
 # activates the workflow when there is a push or pull request in the repo
env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
jobs:
  test_project:
    runs-on: ubuntu-latest # operating system your code will run on
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt # install all our dependencies for the project        
      - name: format code
        id: autoyapf
        uses: mritunjaysharma394/autoyapf@v2
        with:
          args: --style pep8 --recursive --in-place .
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: run tests  
        run: |
          cd todo_app_api
          python manage.py makemigrations
          python manage.py migrate
          python manage.py test
      
      

